FROM lomik/graphite-clickhouse:v0.11.1

COPY ./root/etc/graphite-clickhouse/rollup.xml /etc/graphite-clickhouse/rollup.xml
COPY ./root/etc/graphite-clickhouse/graphite-clickhouse.conf /etc/graphite-clickhouse/graphite-clickhouse.conf
