FROM yandex/clickhouse-server:20.3.5.21

COPY ./root/etc/clickhouse-server/config.d/rollup.xml /etc/clickhouse-server/config.d/rollup.xml
COPY ./root/etc/clickhouse-server/config.d/metrics.xml /etc/clickhouse-server/config.d/metrics.xml
