{
 "title": "Graphite-clickhouse",
 "tags": [ "monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Carbon-clickhouse [ metricsReceived ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sortByMaxima(resources.monitoring.carbon-clickhouse.*.tcp.metricsReceived), 1)), 'count')"
    }
   ]
  },
  {
   "title": "clickhouse-servers [ Queries  ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(resources.monitoring.clickhouse.*.*.*.InsertQuery))"
    },
    {
     "target": "aliasByMetric(sumSeries(resources.monitoring.clickhouse.*.*.*.SelectQuery))"
    }
   ]
  },
  {
   "title": "CarbonAPI [ Mem alloc ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(nonNegativeDerivative(resources.monitoring.carbonapi.*.total_alloc), 3)), 'Total')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasByMetric(servers.apphost.cpu-total.*.*_{user,system,softirq,w*})), 'usage_', '\\1')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(sortByMaxima(aliasByMetric(servers.apphost.mem.{used,buffered,slab_recl,ca*})), 'usage_', '\\1')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(servers.*.system.load1, 'shortterm')"
    },
    {
     "target": "alias(servers.*.system.load5, 'midterm')"
    },
    {
     "target": "alias(servers.*.system.load15, 'longterm')"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(scale(servers.*.sd*.*.io_time, 0.1)), 2, 5)"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.*-_Private.*.*.*.*.used_percent, 2)"
    },
    {
     "target": "aliasByNode(servers.*.sd*.*.*.*.*.used_percent, 2, 5)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(servers.*.eth0.net.bytes_sent), 4)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(servers.*.eth0.net.bytes_recv), 4)"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(servers.*.eth0.net.drop_*)), 'drop')"
    }
   ]
  },
  { "title": "StatsD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "bioyino [ingress]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(resources.monitoring.bioyino.ingress*, 3)"
    }
   ]
  },
  {
   "title": "bioyino [egress]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(resources.monitoring.bioyino.egress, 3)"
    }
   ]
  },
  {
   "title": "bioyino [errors]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(resources.monitoring.bioyino.{*-error,drop})"
    }
   ]
  }
 ]
}